# Generated by Django 4.2.3 on 2024-08-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_id_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
