services:
  db:
    container_name: postgresql
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - .env
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - /ft_transcendence/backend
      - ./backend:/backend
    ports:
      - 8000:8000
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173


  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8080:8080"







