version: '3'
services:
  db:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /home/npatron/Documents/ft_transcendence/app
      - ./app:/app
    ports:                                                 
      - 8000:8000 

  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data:






