services:
  db:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: