# Generated by Django 4.2.3 on 2024-08-26 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendsList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=10),
        ),
    ]
