# Generated by Django 4.2.3 on 2024-08-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_lastvisit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_subscription',
        ),
        migrations.AddField(
            model_name='user',
            name='isFrom42',
            field=models.BooleanField(default=False),
        ),
    ]
