# Generated by Django 4.2.3 on 2024-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.JSONField()),
            ],
        ),
    ]
