# Generated by Django 4.2.3 on 2024-09-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_waitinginvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitingInvitation',
        ),
    ]
