# Generated by Django 4.2.3 on 2024-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_waitinginvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitList', models.JSONField()),
            ],
        ),
    ]
