# Generated by Django 4.2.3 on 2024-09-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_waitinginvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitationFrom', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='WaitingInvitation',
        ),
    ]
