# Generated by Django 4.2.3 on 2024-09-13 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_invitation_delete_waitinginvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitationFrom',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='to',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='type',
        ),
        migrations.AddField(
            model_name='invitation',
            name='expeditor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='send_invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receive_invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
