# Generated by Django 4.2.3 on 2024-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_invitation_expeditor_alter_invitation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='parse',
            field=models.CharField(default=None, max_length=125),
        ),
    ]
