# Generated by Django 4.2.3 on 2024-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_friendslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendslist',
            name='parse',
            field=models.CharField(default=None, max_length=125),
        ),
    ]
