# Generated by Django 4.2.3 on 2024-09-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_friendslist_parse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friendsList',
        ),
    ]
