# Generated by Django 4.2.3 on 2024-10-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_user_friendslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='langue',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
