# Generated by Django 4.2.3 on 2024-10-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_langue'),
        ('users', '0026_relationsblocked'),
    ]

    operations = [
    ]
