# Generated by Django 4.2.3 on 2024-10-23 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_merge_0024_user_langue_0026_relationsblocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('userInvited', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userInvited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
