# Generated by Django 4.2.3 on 2024-10-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
    ]
