# Generated by Django 4.2.3 on 2024-10-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_gameinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='roomId',
            field=models.CharField(default=None, max_length=125),
        ),
    ]
